---
- hosts: all
  become: yes
  gather_facts: yes
  environment:
    http_proxy: http://proxy-ics.external.lmco.com:80
    https_proxy: http://proxy-ics.external.lmco.com:80
  roles:
    - nephelaiio.nfs
    - ehime.packer-rhel
